with open('Lynx_input_parameters.txt', 'w') as f:
    f.write('min_rep_age 3')
    f.write('max_rep_age 12')
    f.write('max_age 16')
    f.write('Tsize 2')
    f.write('litter_size 1.9')
    f.write('litter_size_sd 0.54')
    f.write('rep_prob 0.57')
    f.write('surv_cub 0.384')
    f.write('surv_sub 0.599')
    f.write('surv_resident 0.798')
    f.write('surv_disperse 0.798')
    f.write('surv_disp_rho 5.8')
    f.write('surv_old 0.594')
    f.write('alpha_steps 0.00027')
    f.write('theta_d 0.4')
    f.write('theta_delta 0.65')
    f.write('delta_theta_long 0.27')
    f.write('delta_theta_f 0.1')
    f.write('L 6')
    f.write('N_d 5')
    f.write('beta 0.8')
    f.write('gamma 0.09')
    f.write('max_years 30')
    f.write('n_cycles 3')
    f.write('n_months_above_R_threshold 12')
    f.write('create_maps 1')
    f.write('mapname input_data/maps/Lynx_HabitatMap_test.txt')
    f.write('mapPops input_data/maps/Lynx_populations_test.txt')
    f.write('start_pop_file input_data/Lynx_start_pop_file_test.txt')
    f.write('reintro_file input_data/Lynx_reintroduced_ind_test.txt')


with open('Rabbit_input_parameters.txt', 'w') as f:
    f.write('max_age 82')
    f.write('juv_age 4')
    f.write('sub_adult_age 6')
    f.write('disp_age 5')
    f.write('MeanLitSize 3.5')
    f.write('SdLitSize 1')
    f.write('r_int -2')
    f.write('r_dens_effect 3')
    f.write('r_second_effect 1')
    f.write('r_later_effect 5')
    f.write('kCapacity_high 14')
    f.write('kCapacity_low 10')
    f.write('MortP_at_month_old 0.5')
    f.write('s_int 8')
    f.write('s_extra_juv 3')
    f.write('s_dens_effect 3')
    f.write('s_food_effect 20')
    f.write('lambda 0.1')
    f.write('dens_opt 3')
    f.write('sigma 2.5')
    f.write('threshold_density_for_lynx 5')
    f.write('mapname_rabbit input_data/maps/Rabbit_HabitatMap_test.txt')
    f.write('breedname input_data/breeding_months_500_test.txt')
    f.write('dryname input_data/consecutive_dry_months_500_test.txt')
    

    




